# Generated by Django 5.1.1 on 2024-10-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Visualizar Catálogo de Vehículos'),)},
        ),
    ]
